---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86184.
--- DateTime: 2023/2/14 16:33
---

--- url
baseUrl = 'http://localhost/game'
baseAIUrl = 'http://localhost/game/ai/'

SpawnAIUrl = baseAIUrl .. 'SpawnAi'
GetAIDropListUrl = baseAIUrl .. 'GetAIDropList?troopid=%d&type=%d&agentid=%d'
GetAIAttributeUrl = baseAIUrl .. 'GetAiattribute?version=%d'
GetChestAndCarriageUrl = baseAIUrl .. 'G'

PostAIAttributeUrl = baseAIUrl .. 'GetAiattribute'

-- triggers
ti_before_mission_start = -19.0 --#can only be used in module_mission_templates triggers
ti_after_mission_start = -20.0 --#can only be used in module_mission_templates triggers
ti_tab_pressed = -21.0 --#can only be used in module_mission_templates triggers
ti_inventory_key_pressed = -22.0 --#can only be used in module_mission_templates triggers
ti_escape_pressed = -23.0 --#can only be used in module_mission_templates triggers
ti_battle_window_opened = -24.0 --#can only be used in module_mission_templates triggers
ti_on_agent_spawn = -25.0 --#can only be used in module_mission_templates triggers
ti_on_agent_killed_or_wounded = -26.0 --#can only be used in module_mission_templates triggers
ti_on_agent_knocked_down = -27.0 --#can only be used in module_mission_templates triggers
ti_on_agent_hit = -28.0 --#can only be used in module_mission_templates triggers
ti_once = 100000000.0

-- presentation flag
tf_left_align = 0x00000004
tf_right_align = 0x00000008
tf_center_justify = 0x00000010
tf_double_space = 0x00000800
tf_vertical_align_center = 0x00001000
tf_scrollable = 0x00002000
tf_single_line = 0x00008000
tf_with_outline = 0x00010000
tf_scrollable_style_2 = 0x00020000

prsntf_read_only = 0x00000001
prsntf_manual_end_only = 0x00000002

-- item type
itp_type_horse = 0x1
itp_type_one_handed_wpn = 0x2
itp_type_two_handed_wpn = 0x3
itp_type_polearm = 0x4
itp_type_arrows = 0x5
itp_type_bolts = 0x6
itp_type_shield = 0x0000000000000007
itp_type_bow = 0x0000000000000008
itp_type_crossbow = 0x0000000000000009
itp_type_thrown = 0x000000000000000a
itp_type_goods = 0x000000000000000b
itp_type_head_armor = 0x000000000000000c
itp_type_body_armor = 0x000000000000000d
itp_type_foot_armor = 0x000000000000000e
itp_type_hand_armor = 0x000000000000000f
itp_type_pistol = 0x0000000000000010
itp_type_musket = 0x0000000000000011
itp_type_bullets = 0x0000000000000012
itp_type_animal = 0x0000000000000013
itp_type_book = 0x0000000000000014

key_1 = 0x02
key_2 = 0x03
key_3 = 0x04
key_4 = 0x05
key_5 = 0x06
key_6 = 0x07
key_7 = 0x08
key_8 = 0x09
key_9 = 0x0a
key_0 = 0x0b
key_a = 0x1e
key_b = 0x30
key_c = 0x2e
key_d = 0x20
key_e = 0x12
key_f = 0x21
key_g = 0x22
key_h = 0x23
key_i = 0x17
key_j = 0x24
key_k = 0x25
key_l = 0x26
key_m = 0x32
key_n = 0x31
key_o = 0x18
key_p = 0x19
key_q = 0x10
key_r = 0x13
key_s = 0x1f
key_t = 0x14
key_u = 0x16
key_v = 0x2f
key_w = 0x11
key_x = 0x2d
key_y = 0x15
key_z = 0x2c
key_numpad_0 = 0x52
key_numpad_1 = 0x4f
key_numpad_2 = 0x50
key_numpad_3 = 0x51
key_numpad_4 = 0x4b
key_numpad_5 = 0x4c
key_numpad_6 = 0x4d
key_numpad_7 = 0x47
key_numpad_8 = 0x48
key_numpad_9 = 0x49
key_num_lock = 0x45
key_numpad_slash = 0xb5
key_numpad_multiply = 0x37
key_numpad_minus = 0x4a
key_numpad_plus = 0x4e
key_numpad_enter = 0x9c
key_numpad_period = 0x53
key_insert = 0xd2
key_delete = 0xd3
key_home = 0xc7
key_end = 0xcf
key_page_up = 0xc9
key_page_down = 0xd1
key_up = 0xc8
key_down = 0xd0
key_left = 0xcb
key_right = 0xcd
key_f1 = 0x3b
key_f2 = 0x3c
key_f3 = 0x3d
key_f4 = 0x3e
key_f5 = 0x3f
key_f6 = 0x40
key_f7 = 0x41
key_f8 = 0x42
key_f9 = 0x43
key_f10 = 0x44
key_f11 = 0x57
key_f12 = 0x58
key_space = 0x39
key_escape = 0x01
key_enter = 0x1c
key_tab = 0x0f
key_back_space = 0x0e
key_open_braces = 0x1a
key_close_braces = 0x1b
key_comma = 0x33
key_period = 0x34
key_slash = 0x35
key_back_slash = 0x2b
key_equals = 0x0d
key_minus = 0x0c
key_semicolon = 0x27
key_apostrophe = 0x28
key_tilde = 0x29
key_caps_lock = 0x3a
key_left_shift = 0x2a
key_right_shift = 0x36
key_left_control = 0x1d
key_right_control = 0x9d
key_left_alt = 0x38
key_right_alt = 0xb8
key_left_mouse_button = 0xe0
key_right_mouse_button = 0xe1
key_middle_mouse_button = 0xe2
key_mouse_button_4 = 0xe3
key_mouse_button_5 = 0xe4
key_mouse_button_6 = 0xe5
key_mouse_button_7 = 0xe6
key_mouse_button_8 = 0xe7
key_mouse_scroll_up = 0xee
key_mouse_scroll_down = 0xef

server_event_local_chat = 12

-- op constant
alarmed = 1
peaceful = 0