---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86184.
--- DateTime: 2023/2/16 12:54
---
-- triggers
ti_once = 100000000.0
-------------------------------------------------------------------------------
-- SIMPLE TRIGGERS
-------------------------------------------------------------------------------
ti_simulate_battle = -5.0
ti_on_party_encounter = -6.0

-------------------------------------------------------------------------------
-- MISSION TEMPLATE TRIGGERS
-------------------------------------------------------------------------------
ti_question_answered = -8.0
-- trigger param 1: answer

ti_server_player_joined = -15.0
-- trigger param 1: player id

ti_on_multiplayer_mission_end = -16.0

ti_before_mission_start = -19.0
ti_after_mission_start = -20.0

ti_tab_pressed = -21.0
ti_inventory_key_pressed = -22.0
ti_escape_pressed = -23.0
ti_battle_window_opened = -24.0

ti_on_agent_spawn = -25.0
-- trigger param 1: agent id

ti_on_agent_killed_or_wounded = -26.0
-- trigger param 1: dead agent id
-- trigger param 2: killer agent id
-- trigger param 3: 0 = killed, 1 = wounded
-- trigger result: 1 = force kill, 2 = force wounded

ti_on_agent_knocked_down = -27.0
-- trigger param 1: knocked down agent id
-- trigger param 1: attacker agent id

ti_on_agent_hit = -28.0
-- trigger param 1: hit agent id
-- trigger param 2: attacker agent id
-- trigger param 3: inflicted damage
-- trigger param 4: hit bone
-- trigger param 5: missile item id
-- reg0: attacker item_id
-- pos0: position of the blow, rotation gives the direction of the blow
-- trigger result: if greater than or equal to zero, inflicted damage is set to the value specified

ti_on_player_exit = -29.0
-- trigger param 1: player id

ti_on_leave_area = -30.0

-------------------------------------------------------------------------------
-- SCENE PROP TRIGGERS
-------------------------------------------------------------------------------
ti_on_scene_prop_init = -40.0
-- trigger param 1: instance id

ti_on_scene_prop_hit = -42.0
-- trigger param 1: instance id
-- trigger param 2: hit damage (server only)
-- trigger param 3: attacker agent id (server only)
-- trigger param 4: weapon item id (server only)
-- trigger param 5: weapon item modifier (server only)
-- trigger param 6: missile item id (server only)
-- trigger param 7: missile item modifier (server only)
-- pos1: hit position
-- pos2: x holds attacker agent id, use (set_fixed_point_multiplier, 1)
-- trigger result: if greater than or equal to zero, inflicted damage is set to the value specified

ti_on_scene_prop_destroy = -43.0
-- trigger param 1: instance id
-- trigger param 1: agent id

ti_on_scene_prop_use = -44.0
-- trigger param 1: agent id
-- trigger param 2: instance id

ti_on_scene_prop_is_animating = -45.0
-- trigger param 1: instance id
-- trigger param 2: remaining animation time

ti_on_scene_prop_animation_finished = -46.0
-- trigger param 1: instance id

ti_on_scene_prop_start_use = -47.0
-- trigger param 1: agent id
-- trigger param 2: instance id

ti_on_scene_prop_cancel_use = -48.0
-- trigger param 1: agent id
-- trigger param 2: instance id

ti_scene_prop_deformation_finished = -76.0
-- trigger param 1: instance id

-------------------------------------------------------------------------------
-- ITEM TRIGGERS
-------------------------------------------------------------------------------
ti_on_init_item = -50.0
-- trigger param 1: agent id
-- trigger param 2: troop id

ti_on_weapon_attack = -51.0
-- trigger param 1: attacker agent id
-- pos1: weapon item position

ti_on_missile_hit = -52.0
-- trigger param 1: shooter agent id
-- trigger param 2: collision_type: 0 = world terrain, 1 = hostile agent, 2 = dynamic prop, 3 = world prop (flora), 4 = mission object (scene prop), 8 = friendly agent, 9 = neutral agent, 10 = under water
-- pos1: missile position

ti_on_shield_hit = -80.0
-- trigger param 1: defender agent id
-- trigger param 2: attacker agent id
-- trigger param 3: inflicted damage
-- trigger param 4: weapon item id
-- trigger param 5: missile item id
-- trigger result: if set, override damage dealt to shield

-------------------------------------------------------------------------------
-- MISSION TEMPLATE TRIGGERS
-------------------------------------------------------------------------------
ti_on_item_picked_up = -53.0
-- trigger param 1: agent id
-- trigger param 2: item id
-- trigger param 3: prop instance id (will be deleted after this trigger)

ti_on_item_dropped = -54.0
-- trigger param 1: agent id
-- trigger param 2: item id
-- trigger param 3: prop instance id

ti_on_agent_mount = -55.0
-- trigger param 1: agent id
-- trigger param 2: horse agent id

ti_on_agent_dismount = -56.0
-- trigger param 1: agent id
-- trigger param 2: horse agent id

ti_on_item_wielded = -57.0
-- trigger param 1: agent id
-- trigger param 2: item id

ti_on_item_unwielded = -58.0
-- trigger param 1: agent id
-- trigger param 2: item id

ti_on_order_issued = -71.0
-- trigger param 1: order no
-- trigger param 2: agent id

-------------------------------------------------------------------------------
-- PRESENTATION TRIGGERS
-------------------------------------------------------------------------------
ti_on_presentation_load = -60.0

ti_on_presentation_run = -61.0
-- trigger param 1: current time in miliseconds

ti_on_presentation_event_state_change = -62.0
-- trigger param 1: object (overlay) id
-- trigger param 2: value (when available)

ti_on_presentation_mouse_enter_leave = -63.0
-- trigger param 1: object (overlay) id that the mouse enters or leaves
-- trigger param 2: 0 = enters, 1 = leaves

ti_on_presentation_mouse_press = -64.0
-- trigger param 1: object(overlay) id that the mouse is pressed on
-- trigger param 2: 0 = left button, 1 = right button, 2 = middle button

-------------------------------------------------------------------------------
-- MAP TRIGGERS
-------------------------------------------------------------------------------
ti_on_init_map_icon = -70.0
-- trigger param 1: id of the owner party

ti_on_switch_to_map = -75.0
